name: CI

on:
  push: ~

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
          validate-wrappers: true

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Verify plugin
        run: ./gradlew verifyPlugin
